// Persistence layer for the active license. The Prisma `License` table is
// effectively a singleton per install — there's only ever one row that the
// app considers "current" (the most-recently-validated, non-deleted one).
//
// The license key is encrypted with Electron `safeStorage` (DPAPI on Windows)
// so it's protected at rest by the OS user account, same pattern as the
// existing `ApiCredential` rows.

import { safeStorage } from 'electron';
import { getPrisma } from '../../db';

export type LicenseSlug = 'isitube' | 'isitubepro';
export type LicensePlanKey = 'iniciante' | 'pro';

export type StoredLicense = {
  /** Decrypted license key. */
  licenseKey: string;
  hwid: string;
  slug: LicenseSlug;
  plan: LicensePlanKey;
  expiresAt: Date | null;
  graceUntil: Date | null;
  subscriptionUrl: string | null;
  supportUrl: string | null;
  lastValidatedAt: Date;
  /** Full validate response payload — used to drive UI in offline grace. */
  lastResponseJson: string;
};

function ensureEncryptionAvailable(): void {
  if (!safeStorage.isEncryptionAvailable()) {
    throw new Error(
      'Criptografia segura indisponível neste sistema (safeStorage). ' +
        'No Windows isso geralmente indica perfil de usuário corrompido.'
    );
  }
}

/**
 * Return the currently-stored license, decrypted. Returns null when there's
 * no row, or when decryption fails (e.g., DB copied from another Windows
 * user account — treated as "no license" so the app falls back to the gate
 * modal).
 */
export async function loadStoredLicense(): Promise<StoredLicense | null> {
  const row = await getPrisma().license.findFirst({
    where: { deletedAt: null },
    orderBy: { lastValidatedAt: 'desc' },
  });
  if (!row) return null;

  if (!safeStorage.isEncryptionAvailable()) return null;

  let licenseKey: string;
  try {
    licenseKey = safeStorage.decryptString(Buffer.from(row.licenseKey));
  } catch {
    return null;
  }

  return {
    licenseKey,
    hwid: row.hwid,
    slug: row.slug as LicenseSlug,
    plan: row.plan as LicensePlanKey,
    expiresAt: row.expiresAt,
    graceUntil: row.graceUntil,
    subscriptionUrl: row.subscriptionUrl,
    supportUrl: row.supportUrl,
    lastValidatedAt: row.lastValidatedAt,
    lastResponseJson: row.lastResponseJson,
  };
}

/**
 * Upsert the current license. If a row already exists, replaces it in place
 * (we keep singleton-ness at the app layer). If not, creates a new one.
 */
export async function saveStoredLicense(input: StoredLicense): Promise<void> {
  ensureEncryptionAvailable();
  const encryptedKey = safeStorage.encryptString(input.licenseKey);

  const prisma = getPrisma();
  const existing = await prisma.license.findFirst({
    where: { deletedAt: null },
    orderBy: { lastValidatedAt: 'desc' },
  });

  const data = {
    // Prisma's generated Bytes type wants Uint8Array<ArrayBuffer>; newer
    // @types/node makes Buffer default to Uint8Array<ArrayBufferLike>. Cast
    // through unknown to bridge — runtime is fine, Buffer extends Uint8Array.
    // (Same pattern is needed in credentials.ts for the same reason.)
    licenseKey: encryptedKey as unknown as Uint8Array<ArrayBuffer>,
    hwid: input.hwid,
    slug: input.slug,
    plan: input.plan,
    expiresAt: input.expiresAt,
    graceUntil: input.graceUntil,
    subscriptionUrl: input.subscriptionUrl,
    supportUrl: input.supportUrl,
    lastValidatedAt: input.lastValidatedAt,
    lastResponseJson: input.lastResponseJson,
  };

  if (existing) {
    await prisma.license.update({ where: { id: existing.id }, data });
  } else {
    await prisma.license.create({ data });
  }
}

/**
 * Soft-delete every license row. Used when the user removes their license
 * key ("trocar chave") or when both two-slug discovery attempts return
 * `invalid` on a revalidation (license truly revoked or wrong).
 */
export async function clearStoredLicense(): Promise<void> {
  await getPrisma().license.updateMany({
    where: { deletedAt: null },
    data: { deletedAt: new Date() },
  });
}
