import { registerSettingsHandlers } from './settings';
import { registerCredentialsHandlers } from './credentials';
import { registerAIHandlers } from './ai';
import { registerIdeasHandlers } from './ideas';
import { registerKeywordsHandlers } from './keywords';
import { registerChannelsHandlers } from './channels';
import { registerScheduleHandlers } from './schedule';
import { registerVideosHandlers } from './videos';
import { registerLibraryHandlers } from './library';
import { registerKanbanHandlers } from './kanban';
import { registerSearchHandlers } from './search';
import { registerTranscriptsHandlers } from './transcripts';
import { registerThumbnailsHandlers } from './thumbnails';
import { registerYoutubeHandlers } from './youtube';
import { registerLicenseHandlers } from './license';
import { registerDialogHandlers } from './dialog';
import { registerBackupHandlers } from './backup';
import { registerCategoriesHandlers } from './categories';
import { registerUpdatesHandlers } from './updates';
import { registerQuotaHandlers } from './quota';
import { registerHealthHandlers } from './health';
import { registerScheduleIpc } from './schedules';

export function registerIpcHandlers(): void {
  registerSettingsHandlers();
  registerCredentialsHandlers();
  registerAIHandlers();
  registerIdeasHandlers();
  registerKeywordsHandlers();
  registerChannelsHandlers();
  registerScheduleHandlers();
  registerVideosHandlers();
  registerLibraryHandlers();
  registerKanbanHandlers();
  registerSearchHandlers();
  registerTranscriptsHandlers();
  registerThumbnailsHandlers();
  registerYoutubeHandlers();
  registerLicenseHandlers();
  registerDialogHandlers();
  registerBackupHandlers();
  registerCategoriesHandlers();
  registerUpdatesHandlers();
  registerQuotaHandlers();
  registerHealthHandlers();
  registerScheduleIpc();
}
